### ISSUE TITLE
Nothing `Touchable` allowed inside modal...?

### ISSUE THREAD

**Issue by rpastorelle** [fomahaut/React-Native-Swipeable-Modal#9]
This is a pretty cool modal but the PanResponder is a bit too controlling... Is there no way to put any kind of `Touchable` component (like a button) inside the modal?

**Comment by cryptobiote** [comment]
+1

**Comment by fomahaut** [comment]
Sorry guys, I remember this issue has been fixed a month ago, but can't find anything on GitHub... (maybe in my dream ?). Anyway, I'll fix it (again) this weekend.

**Comment by fomahaut** [comment]
Fixed in 1.4.0, but take care that there are some breaking changes because of Android support.
